#!/bin/bash

width=$(tput cols)
height=$(tput lines)
BG_BLUE="$(tput setab 4)"
BG_BLACK="$(tput setab 0)"
FG_GREEN="$(tput setaf 2)"
FG_WHITE="$(tput setaf 7)"

# Save screen
# tput smcup like clear
tput smcup

# Display menu until selection == 0
tput cup 0 $(((width / 2) - (length / 2)))
while [[ $REPLY != 0 ]]; do
	clear
	echo -n ${BG_BLUE}${FG_WHITE}
	cat <<- _EOF_
	# ************************************************************************* # 
	#               ██╗   ██╗ █████╗ ██╗████████╗   ███████╗██╗                 #
	#               ╚██╗ ██╔╝██╔══██╗██║╚══██╔══╝   ██╔════╝██║                 #
	#                ╚████╔╝ ███████║██║   ██║█████╗█████╗  ██║█████╗           #
	#                 ╚██╔╝  ██╔══██║██║   ██║╚════╝██╔══╝  ██║╚════╝           #
	#                  ██║   ██║  ██║██║   ██║      ███████╗███████╗            #
	#                  ╚═╝   ╚═╝  ╚═╝╚═╝   ╚═╝      ╚══════╝╚══════╝            #
	#                                                                           #
	#    Please Select:                                                         #
	#                                                                           #
	#  1. Get the Weather Report                                                #
	#  2. Find Your External IP Address                                         #
	#  3. Cryptocurrency based on realtime exchange rates of the top 10 cryptos #
	#  0. Quit                                                                  #
	# ************************************************************************* #


	_EOF_

	read -p "Enter selection [0-3] >  >" selection
	# Clear area beneath menu
	tput cup 18 0
	echo  ${BG_BLACK}${FG_GREEN}
	tput ed
	tput cup 21 0
	# Act on selection
	case $selection in
		1)  read -p "Enter City you want 'you can get even the Moon'>>" City 
			curl -4 wttr.in/$City
			;;
		2) curl ipinfo.io/
			;;
		3) curl usd.rate.sx
			read -p "Enter Coin Show how exchange rate was changing in time >>" Coin
			curl rate.sx/$Coin
			;;
		0) break
			;;
		*) echo "Invalid entry"
			;;
	esac
	echo "\n\nPress any Key to continue."
	read -n 1
done
#Restore screen
tput smcup
echo "program Terminated. "
